' Gambas module file

'Ported from Lyrics Finder 0.3.2
'Porting instructions
'replace -- by '
'replace single quotes by double quotes
'check regexes
'transform :gsub into string.gsub, and string.gsub into replace
'replace LCase by LCase
'replace local by dim .. as ..
'replace end by end if
'replace string.find with InStr
'replace .. by &
'replace :sub by Mid

'Public title_x As String = "As Long As You Follow"
Public title_x As String
'Public artist_x As String = "Fleetwood Mac"
Public artist_x As String
Public filename As String

Public Function get_lyrics(filenamelocal As String) As String
    filename = getCleanFilename(filenamelocal)
    Return fetch_lyrics()
End

Function fetch_lyrics() As String
    
    Dim Client As New HttpClient
    Dim data As String
    Dim apiurl As String
    
    'Url
    filename = Replace(filename, " ", "%20")
    filename = Replace(filename, "&", "and")
    'filename = Replace(filename, "&", "%26")
    'filename = Replace(filename, "'", "%27")
    
    apiurl = "http://hugsmile.eu/lyricscore/api/v1/?filename=" & filename & "&format=text"

    Client.URL = apiurl
    Client.Async = False
    'Client.Timeout = intTimeOut
    Client.UserAgent = "text2srt"
    Print "Fetch " & apiurl
    Client.Get()
    
    If Client.Status < 0 Then
        Print "Error " & Client.Status & " at " & Client.URL
    Else
        If Lof(Client) Then data = Read #Client, Lof(Client)
        
       
        
    End If
    
    Return data
    
End


Public Function getCleanFilename(filename As String) As String
    
    Dim locationdot As Integer
    Dim locationslash As Integer
    Dim locationparenthesis As Integer
    
    locationslash = RInStr(filename, "/") 
    filename = Mid(filename, locationslash + 1)
    locationdot = RInStr(filename, ".")
    filename = Mid(filename, 1, locationdot)
    locationparenthesis = RInStr(filename, "(")
    filename = Mid(filename, 1, locationparenthesis - 1)
    
    Return filename
    
End
